# Generated by Django 6.0.1 on 2026-02-01 18:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='设备唯一标识，格式: AA:BB:CC:DD:EE:FF', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='MAC 地址格式必须为 AA:BB:CC:DD:EE:FF', regex='^([0-9A-F]{2}:){5}[0-9A-F]{2}$')], verbose_name='MAC 地址')),
                ('name', models.CharField(help_text='用户自定义的设备名称', max_length=100, verbose_name='设备名称')),
                ('description', models.TextField(blank=True, help_text='设备描述信息', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, help_text='设备是否处于激活状态', verbose_name='激活状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='最后一次接收到数据的时间', null=True, verbose_name='最后上报时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detectors', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '探测器',
                'verbose_name_plural': '探测器',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='core_detect_owner_i_afcbf6_idx'), models.Index(fields=['is_active', '-last_seen_at'], name='core_detect_is_acti_bbfed2_idx')],
            },
        ),
    ]
