# Generated by Django 6.0.1 on 2026-02-01 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='mac_address',
            field=models.CharField(help_text='设备唯一标识, 格式: AA:BB:CC:DD:EE:FF', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='MAC 地址格式必须为 AA:BB:CC:DD:EE:FF', regex='^([0-9A-F]{2}:){5}[0-9A-F]{2}$')], verbose_name='MAC 地址'),
        ),
    ]
