# Generated by Django 6.0.1 on 2026-02-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_detector_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text="例如: 'exception', 'startup', 'config_change'", max_length=50, verbose_name='事件类型')),
                ('payload', models.JSONField(default=dict, help_text='事件详细信息(JSON格式)', verbose_name='事件数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发生时间')),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.detector', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '系统事件',
                'verbose_name_plural': '系统事件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['detector', '-created_at'], name='core_event_detecto_9482b2_idx')],
            },
        ),
    ]
