log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://doc.traefik.io/traefik/https/acme/#lets-encrypt
    acme:
      email: "ops@cosray.top"
      storage: /etc/traefik/acme/acme.json
      # https://doc.traefik.io/traefik/https/acme/#tlschallenge
      tlsChallenge: {}

http:
  routers:
    web-router:
      rule: "Host(`cosray.top`)"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

    web-ip-health-router:
      rule: "Host(`cosray.top`) && Path(`/api/health`)"
      entryPoints:
        - web
      service: django

    web-media-router:
      rule: "Host(`cosray.top`) && (PathPrefix(`/media/`) || PathPrefix(`/static/`))"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django-media

    web-secure-router:
      rule: "Host(`cosray.top`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    web-secure-media-router:
      rule: "Host(`cosray.top`) && (PathPrefix(`/media/`) || PathPrefix(`/static/`))"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://doc.traefik.io/traefik/master/middlewares/http/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  # https://doc.traefik.io/traefik/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
