log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "ops@cosray.top"
      storage: /etc/traefik/acme/acme.json
      tlsChallenge: {}

http:
  routers:
    web-secure-router:
      rule: "Host(`cosray.top`)"
      entryPoints:
        - websecure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    web-secure-health-router:
      rule: "Host(`cosray.top`) && Path(`/api/health`)"
      entryPoints:
        - websecure
      service: django
      tls:
        certResolver: letsencrypt

    web-secure-media-router:
      rule: "Host(`cosray.top`) && (PathPrefix(`/media/`) || PathPrefix(`/static/`))"
      entryPoints:
        - websecure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: false
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
